/*!
 * Knockout JavaScript library v3.2.0
 * (c) Steven Sanderson - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {var DEBUG=!1;
(function(q){var w=this||(0,eval)("this"),y=w.document,Q=w.navigator,t=w.jQuery,G=w.JSON;(function(q){"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?q(module.exports||exports,require):"function"===typeof define&&define.amd?define(["exports","require"],q):q(w.ko={})})(function(R,S){function L(a,c){return null===a||typeof a in U?a===c:!1}function V(a,c){var d;return function(){d||(d=setTimeout(function(){d=q;a()},c))}}function W(a,c){var d;return function(){clearTimeout(d);d=
setTimeout(a,c)}}function N(b,c,d,e){a.bindingHandlers[b]={init:function(b,h,k,g,l){var m,r;a.computed(function(){var g=a.utils.unwrapObservable(h()),p=!d!==!g,k=!r;if(k||c||p!==m)k&&a.computedContext.getDependenciesCount()&&(r=a.utils.cloneNodes(a.virtualElements.childNodes(b),!0)),p?(k||a.virtualElements.setDomNodeChildren(b,a.utils.cloneNodes(r)),a.applyBindingsToDescendants(e?e(l,g):l,b)):a.virtualElements.emptyNode(b),m=p},null,{disposeWhenNodeIsRemoved:b});return{controlsDescendantBindings:!0}}};
a.expressionRewriting.bindingRewriteValidators[b]=!1;a.virtualElements.allowedBindings[b]=!0}var a="undefined"!==typeof R?R:{};a.exportSymbol=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.exportProperty=function(a,c,d){a[c]=d};a.version="3.2.0";a.exportSymbol("version",a.version);a.utils=function(){function b(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function d(a,
b){a.__proto__=b;return a}var e={__proto__:[]}instanceof Array,f={},h={},k=Q&&/Firefox\/2/i.test(Q.userAgent)?"KeyboardEvent":"UIEvents";f[k]=["keyup","keydown","keypress"];f.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(f,function(a,b){if(b.length)for(var c=0,d=b.length;c<d;c++)h[b[c]]=a});var g={propertychange:!0},l=y&&function(){for(var a=3,b=y.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+
"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:q}();return{fieldsIncludedWithJsonPost:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],arrayForEach:function(a,b){for(var c=0,d=a.length;c<d;c++)b(a[c],c)},arrayIndexOf:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},arrayFirst:function(a,b,c){for(var d=0,g=a.length;d<g;d++)if(b.call(c,a[d],d))return a[d];return null},arrayRemoveItem:function(b,
c){var d=a.utils.arrayIndexOf(b,c);0<d?b.splice(d,1):0===d&&b.shift()},arrayGetDistinctValues:function(b){b=b||[];for(var c=[],d=0,g=b.length;d<g;d++)0>a.utils.arrayIndexOf(c,b[d])&&c.push(b[d]);return c},arrayMap:function(a,b){a=a||[];for(var c=[],d=0,g=a.length;d<g;d++)c.push(b(a[d],d));return c},arrayFilter:function(a,b){a=a||[];for(var c=[],d=0,g=a.length;d<g;d++)b(a[d],d)&&c.push(a[d]);return c},arrayPushAll:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<
d;c++)a.push(b[c]);return a},addOrRemoveItem:function(b,c,d){var g=a.utils.arrayIndexOf(a.utils.peekObservable(b),c);0>g?d&&b.push(c):d||b.splice(g,1)},canSetPrototype:e,extend:c,setPrototypeOf:d,setPrototypeOfOrExtend:e?d:c,objectForEach:b,objectMap:function(a,b){if(!a)return a;var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b(a[d],d,a));return c},emptyDomNode:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},moveCleanedNodesToContainerElement:function(b){b=a.utils.makeArray(b);for(var c=
y.createElement("div"),d=0,g=b.length;d<g;d++)c.appendChild(a.cleanNode(b[d]));return c},cloneNodes:function(b,c){for(var d=0,g=b.length,e=[];d<g;d++){var l=b[d].cloneNode(!0);e.push(c?a.cleanNode(l):l)}return e},setDomNodeChildren:function(b,c){a.utils.emptyDomNode(b);if(c)for(var d=0,g=c.length;d<g;d++)b.appendChild(c[d])},replaceDomNodes:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var g=d[0],e=g.parentNode,l=0,f=c.length;l<f;l++)e.insertBefore(c[l],g);l=0;for(f=d.length;l<f;l++)a.removeNode(d[l])}},
fixUpContinuousNodeArray:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.shift();if(1<a.length){var c=a[0],d=a[a.length-1];for(a.length=0;c!==d;)if(a.push(c),c=c.nextSibling,!c)return;a.push(d)}}return a},setOptionNodeSelectionState:function(a,b){7>l?a.setAttribute("selected",b):a.selected=b},stringTrim:function(a){return null===a||a===q?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},stringStartsWith:function(a,b){a=a||"";return b.length>
a.length?!1:a.substring(0,b.length)===b},domNodeIsContainedBy:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(3===a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},domNodeIsAttachedToDocument:function(b){return a.utils.domNodeIsContainedBy(b,b.ownerDocument.documentElement)},anyDomNodeIsAttachedToDocument:function(b){return!!a.utils.arrayFirst(b,a.utils.domNodeIsAttachedToDocument)},
tagNameLower:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},registerEventHandler:function(b,c,d){var e=l&&g[c];if(!e&&t)t(b).bind(c,d);else if(e||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var f=function(a){d.call(b,a)},h="on"+c;b.attachEvent(h,f);a.utils.domNodeDisposal.addDisposeCallback(b,function(){b.detachEvent(h,f)})}else throw Error("Browser doesn't support addEventListener or attachEvent");else b.addEventListener(c,d,!1)},triggerEvent:function(b,
c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var d;"input"===a.utils.tagNameLower(b)&&b.type?"click"!=c.toLowerCase()?d=!1:(d=b.type,d="checkbox"==d||"radio"==d):d=!1;if(t&&!d)t(b).trigger(c);else if("function"==typeof y.createEvent)if("function"==typeof b.dispatchEvent)d=y.createEvent(h[c]||"HTMLEvents"),d.initEvent(c,!0,!0,w,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&
b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");},unwrapObservable:function(b){return a.isObservable2(b)?b():b instanceof F?b.get():b},peekObservable:function(b){return a.isObservable2(b)?b.peek():b instanceof F?b.peek():b},toggleDomNodeCssClass:function(b,d,c){if(d){var g=/\S+/g,e=b.className.match(g)||[];a.utils.arrayForEach(d.match(g),function(b){a.utils.addOrRemoveItem(e,b,c)});b.className=e.join(" ")}},
setTextContent:function(b,d){var c=a.utils.unwrapObservable(d);if(null===c||c===q)c="";var g=a.virtualElements.firstChild(b);!g||3!=g.nodeType||a.virtualElements.nextSibling(g)?a.virtualElements.setDomNodeChildren(b,[b.ownerDocument.createTextNode(c)]):g.data=c;a.utils.forceRefresh(b)},setElementName:function(a,b){a.name=b;if(7>=l)try{a.mergeAttributes(y.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},forceRefresh:function(a){9<=l&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=
a.style.zoom))},ensureSelectElementIsRenderedCorrectly:function(a){if(l){var b=a.style.width;a.style.width=0;a.style.width=b}},range:function(b,c){b=a.utils.unwrapObservable(b);c=a.utils.unwrapObservable(c);for(var d=[],g=b;g<=c;g++)d.push(g);return d},makeArray:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},isIe6:6===l,isIe7:7===l,ieVersion:l,getFormFields:function(b,c){for(var d=a.utils.makeArray(b.getElementsByTagName("input")).concat(a.utils.makeArray(b.getElementsByTagName("textarea"))),
g="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},e=[],l=d.length-1;0<=l;l--)g(d[l])&&e.push(d[l]);return e},parseJson:function(b){return"string"==typeof b&&(b=a.utils.stringTrim(b))?G&&G.parse?G.parse(b):(new Function("return "+b))():null},stringifyJson:function(b,c,d){if(!G||!G.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");
return G.stringify(a.utils.unwrapObservable(b),c,d)},postJson:function(c,d,g){g=g||{};var e=g.params||{},l=g.includeFields||this.fieldsIncludedWithJsonPost,f=c;if("object"==typeof c&&"form"===a.utils.tagNameLower(c))for(var f=c.action,h=l.length-1;0<=h;h--)for(var k=a.utils.getFormFields(c,l[h]),A=k.length-1;0<=A;A--)e[k[A].name]=k[A].value;d=a.utils.unwrapObservable(d);var x=y.createElement("form");x.style.display="none";x.action=f;x.method="post";for(var v in d)c=y.createElement("input"),c.type=
"hidden",c.name=v,c.value=a.utils.stringifyJson(a.utils.unwrapObservable(d[v])),x.appendChild(c);b(e,function(a,b){var c=y.createElement("input");c.type="hidden";c.name=a;c.value=b;x.appendChild(c)});y.body.appendChild(x);g.submitter?g.submitter(x):x.submit();setTimeout(function(){x.parentNode.removeChild(x)},0)}}}();a.exportSymbol("utils",a.utils);a.exportSymbol("utils.arrayForEach",a.utils.arrayForEach);a.exportSymbol("utils.arrayFirst",a.utils.arrayFirst);a.exportSymbol("utils.arrayFilter",a.utils.arrayFilter);
a.exportSymbol("utils.arrayGetDistinctValues",a.utils.arrayGetDistinctValues);a.exportSymbol("utils.arrayIndexOf",a.utils.arrayIndexOf);a.exportSymbol("utils.arrayMap",a.utils.arrayMap);a.exportSymbol("utils.arrayPushAll",a.utils.arrayPushAll);a.exportSymbol("utils.arrayRemoveItem",a.utils.arrayRemoveItem);a.exportSymbol("utils.extend",a.utils.extend);a.exportSymbol("utils.fieldsIncludedWithJsonPost",a.utils.fieldsIncludedWithJsonPost);a.exportSymbol("utils.getFormFields",a.utils.getFormFields);a.exportSymbol("utils.peekObservable",
a.utils.peekObservable);a.exportSymbol("utils.postJson",a.utils.postJson);a.exportSymbol("utils.parseJson",a.utils.parseJson);a.exportSymbol("utils.registerEventHandler",a.utils.registerEventHandler);a.exportSymbol("utils.stringifyJson",a.utils.stringifyJson);a.exportSymbol("utils.range",a.utils.range);a.exportSymbol("utils.toggleDomNodeCssClass",a.utils.toggleDomNodeCssClass);a.exportSymbol("utils.triggerEvent",a.utils.triggerEvent);a.exportSymbol("utils.unwrapObservable",a.utils.unwrapObservable);
a.exportSymbol("utils.objectForEach",a.utils.objectForEach);a.exportSymbol("utils.addOrRemoveItem",a.utils.addOrRemoveItem);a.exportSymbol("unwrap",a.utils.unwrapObservable);Function.prototype.bind||(Function.prototype.bind=function(a){var c=this,d=Array.prototype.slice.call(arguments);a=d.shift();return function(){return c.apply(a,d.concat(Array.prototype.slice.call(arguments)))}});a.utils.domData=new function(){function a(b,h){var k=b[d];if(!k||"null"===k||!e[k]){if(!h)return q;k=b[d]="ko"+c++;
e[k]={}}return e[k]}var c=0,d="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var e=a(c,!1);return e===q?q:e[d]},set:function(c,d,e){if(e!==q||a(c,!1)!==q)a(c,!0)[d]=e},clear:function(a){var b=a[d];return b?(delete e[b],a[d]=null,!0):!1},nextKey:function(){return c++ +d}}};a.exportSymbol("utils.domData",a.utils.domData);a.exportSymbol("utils.domData.clear",a.utils.domData.clear);a.utils.domNodeDisposal=new function(){function b(b,c){var g=a.utils.domData.get(b,d);g===q&&c&&(g=[],a.utils.domData.set(b,
d,g));return g}function c(d){var e=b(d,!1);if(e)for(var e=e.slice(0),g=0;g<e.length;g++)e[g](d);a.utils.domData.clear(d);a.utils.domNodeDisposal.cleanExternalData(d);if(f[d.nodeType])for(e=d.firstChild;d=e;)e=d.nextSibling,8===d.nodeType&&c(d)}var d=a.utils.domData.nextKey(),e={1:!0,8:!0,9:!0},f={1:!0,9:!0};return{addDisposeCallback:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},removeDisposeCallback:function(c,e){var g=b(c,!1);g&&(a.utils.arrayRemoveItem(g,
e),0==g.length&&a.utils.domData.set(c,d,q))},cleanNode:function(b){if(e[b.nodeType]&&(c(b),f[b.nodeType])){var d=[];a.utils.arrayPushAll(d,b.getElementsByTagName("*"));for(var g=0,l=d.length;g<l;g++)c(d[g])}return b},removeNode:function(b){a.cleanNode(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){t&&"function"==typeof t.cleanData&&t.cleanData([a])}}};a.cleanNode=a.utils.domNodeDisposal.cleanNode;a.removeNode=a.utils.domNodeDisposal.removeNode;a.exportSymbol("cleanNode",
a.cleanNode);a.exportSymbol("removeNode",a.removeNode);a.exportSymbol("utils.domNodeDisposal",a.utils.domNodeDisposal);a.exportSymbol("utils.domNodeDisposal.addDisposeCallback",a.utils.domNodeDisposal.addDisposeCallback);a.exportSymbol("utils.domNodeDisposal.removeDisposeCallback",a.utils.domNodeDisposal.removeDisposeCallback);a.utils.domNodeReady={domDataKey:a.utils.domData.nextKey()+"_domNodeReady",getReadyCallbacks:function(b,c){var d=a.utils.domData.get(b,this.domDataKey);d||(d=[],a.utils.domData.set(b,
this.domDataKey,d));return d},clearReadyCallback:function(b){a.utils.domData.set(b,this.domDataKey,q)},addReadyCallback:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");this.getReadyCallbacks(a,!0).push(c)},removeReadyCallback:function(b,c){var d=this._getReadyCallbacks(b,!1);d&&(a.utils.arrayRemoveItem(d,c),0==d.length&&this.clearReadyCallback(b))}};a.exportSymbol("utils.domNodeReady",a.utils.domNodeReady);a.exportSymbol("utils.domNodeReady.addReadyCallback",a.utils.domNodeReady.addReadyCallback);
a.exportSymbol("utils.domNodeReady.removeReadyCallback",a.utils.domNodeReady.removeReadyCallback);(function(){a.utils.parseHtmlFragment=function(b){var c;if(t)if(t.parseHTML)c=t.parseHTML(b)||[];else{if((c=t.clean([b]))&&c[0]){for(b=c[0];b.parentNode&&11!==b.parentNode.nodeType;)b=b.parentNode;b.parentNode&&b.parentNode.removeChild(b)}}else{var d=a.utils.stringTrim(b).toLowerCase();c=y.createElement("div");d=d.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!d.indexOf("<tr")&&[2,"<table><tbody>",
"</tbody></table>"]||(!d.indexOf("<td")||!d.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];b="ignored<div>"+d[1]+b+d[2]+"</div>";for("function"==typeof w.innerShiv?c.appendChild(w.innerShiv(b)):c.innerHTML=b;d[0]--;)c=c.lastChild;c=a.utils.makeArray(c.lastChild.childNodes)}return c};a.utils.setHtml=function(b,c){a.utils.emptyDomNode(b);c=a.utils.unwrapObservable(c);if(null!==c&&c!==q)if("string"!=typeof c&&(c=c.toString()),t)t(b).html(c);else for(var d=a.utils.parseHtmlFragment(c),
e=0;e<d.length;e++)b.appendChild(d[e])}})();a.exportSymbol("utils.parseHtmlFragment",a.utils.parseHtmlFragment);a.exportSymbol("utils.setHtml",a.utils.setHtml);a.memoization=function(){function b(c,e){if(c)if(8==c.nodeType){var f=a.memoization.parseMemoText(c.nodeValue);null!=f&&e.push({domNode:c,memoId:f})}else if(1==c.nodeType)for(var f=0,h=c.childNodes,k=h.length;f<k;f++)b(h[f],e)}var c={};return{memoize:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");
var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},unmemoize:function(a,b){var f=c[a];if(f===q)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return f.apply(null,b||[]),!0}finally{delete c[a]}},unmemoizeDomNodeAndDescendants:function(c,e){var f=[];b(c,f);for(var h=0,k=f.length;h<k;h++){var g=f[h].domNode,l=[g];e&&a.utils.arrayPushAll(l,
e);a.memoization.unmemoize(f[h].memoId,l);g.nodeValue="";g.parentNode&&g.parentNode.removeChild(g)}},parseMemoText:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.exportSymbol("memoization",a.memoization);a.exportSymbol("memoization.memoize",a.memoization.memoize);a.exportSymbol("memoization.unmemoize",a.memoization.unmemoize);a.exportSymbol("memoization.parseMemoText",a.memoization.parseMemoText);a.exportSymbol("memoization.unmemoizeDomNodeAndDescendants",a.memoization.unmemoizeDomNodeAndDescendants);
a.extenders={throttle:function(b,c){b.throttleEvaluation=c;var d=null;return a.dependentObservable({read:b,write:function(a){clearTimeout(d);d=setTimeout(function(){b(a)},c)}})},rateLimit:function(a,c){var d,e,f;"number"==typeof c?d=c:(d=c.timeout,e=c.method);f="notifyWhenChangesStop"==e?W:V;a.limit(function(a){return f(a,d)})},notify:function(a,c){a.equalityComparer="always"==c?null:L}};var U={undefined:1,"boolean":1,number:1,string:1};a.exportSymbol("extenders",a.extenders);a.subscription=function(b,
c,d){this.target=b;this.callback=c;this.disposeCallback=d;this.isDisposed=!1;a.exportProperty(this,"dispose",this.dispose)};a.subscription.prototype.dispose=function(){this.isDisposed=!0;this.disposeCallback()};a.subscribable=function(){a.utils.setPrototypeOfOrExtend(this,a.subscribable.fn);this._subscriptions={}};var B={subscribe:function(b,c,d){var e=this;d=d||"change";b=c?b.bind(c):b;var f=new a.subscription(e,b,function(){a.utils.arrayRemoveItem(e._subscriptions[d],f);e.afterSubscriptionRemove&&
e.afterSubscriptionRemove(d)});e.beforeSubscriptionAdd&&e.beforeSubscriptionAdd(d);e._subscriptions[d]||(e._subscriptions[d]=[]);e._subscriptions[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";if(this.hasSubscriptionsForEvent(c))try{a.dependencyDetection.begin();for(var d=this._subscriptions[c].slice(0),e=0,f;f=d[e];++e)f.isDisposed||f.callback(b)}finally{a.dependencyDetection.end()}},limit:function(b){var c=this,d=a.isObservable2(c),e,f,h;c._origNotifySubscribers||(c._origNotifySubscribers=
c.notifySubscribers,c.notifySubscribers=function(a,b){b&&"change"!==b?"beforeChange"===b?c._rateLimitedBeforeChange(a):c._origNotifySubscribers(a,b):c._rateLimitedChange(a)});var k=b(function(){d&&h===c?h=c():a.isObservable(c)&&(h=c.get());e=!1;c.isDifferent(f,h)&&c._origNotifySubscribers(f=h)});c._rateLimitedChange=function(a){e=!0;h=a;k()};c._rateLimitedBeforeChange=function(a){e||(f=a,c._origNotifySubscribers(a,"beforeChange"))}},hasSubscriptionsForEvent:function(a){return this._subscriptions[a]&&
this._subscriptions[a].length},getSubscriptionsCount:function(){var b=0;a.utils.objectForEach(this._subscriptions,function(a,d){b+=d.length});return b},isDifferent:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,c)},extend:function(b){var c=this;b&&a.utils.objectForEach(b,function(b,e){var f=a.extenders[b];"function"==typeof f&&(c=f(c,e)||c)});return c}};a.exportProperty(B,"subscribe",B.subscribe);a.exportProperty(B,"extend",B.extend);a.exportProperty(B,"getSubscriptionsCount",
B.getSubscriptionsCount);a.utils.canSetPrototype&&a.utils.setPrototypeOf(B,Function.prototype);a.subscribable.fn=B;a.isSubscribable=function(a){return null!=a&&"function"==typeof a.subscribe&&"function"==typeof a.notifySubscribers};a.exportSymbol("subscribable",a.subscribable);a.exportSymbol("isSubscribable",a.isSubscribable);a.computedContext=a.dependencyDetection=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=0;return{begin:b,end:c,registerDependency:function(b){if(e){if(!a.isSubscribable(b))throw Error("Only subscribable things can act as dependencies");
e.callback(b,b._id||(b._id=++f))}},ignore:function(a,d,g){try{return b(),a.apply(d,g||[])}finally{c()}},getDependenciesCount:function(){if(e)return e.computed.getDependenciesCount()},isInitial:function(){if(e)return e.isInitial}}}();a.exportSymbol("computedContext",a.computedContext);a.exportSymbol("computedContext.ignore",a.computedContext.ignore);a.exportSymbol("computedContext.getDependenciesCount",a.computedContext.getDependenciesCount);a.exportSymbol("computedContext.isInitial",a.computedContext.isInitial);
a.exportSymbol("computedContext.isSleeping",a.computedContext.isSleeping);var B=function(a){var c=function(){};c.prototype=a.prototype;return new c},F=function(){this._subscriptions={}};F.prototype={};a.utils.extend(F.prototype,a.subscribable.fn);var I=function(a){this.latestValue=a;this._subscriptions={}};I.prototype=B(F);a.utils.extend(I.prototype,{set:function(a){this.isDifferent(this.latestValue,a)&&(this.valueWillMutate(),a={oldValue:this.latestValue,newValue:a},this.valueChange(a),this.latestValue=
a.newValue,this.valueHasMutated());return this},get:function(){a.dependencyDetection.registerDependency(this);return this.latestValue},peek:function(){return this.latestValue},valueHasMutated:function(){this.notifySubscribers(this.latestValue)},valueChange:function(a){this.notifySubscribers(a,"changing")},valueWillMutate:function(){this.notifySubscribers(this.latestValue,"beforeChange")},equalityComparer:L});a.observable=function(a){return new I(a)};a.observable2=function(b){function c(){if(0<arguments.length){if(c.isDifferent(d,
arguments[0])){c.valueWillMutate();var b={oldValue:d,newValue:arguments[0]};c.valueChange(b);d=b.newValue;DEBUG&&(c._latestValue=d);c.valueHasMutated()}return this}a.dependencyDetection.registerDependency(c);return d}var d=b;a.subscribable.call(c);a.utils.setPrototypeOfOrExtend(c,a.observable2.fn);DEBUG&&(c._latestValue=d);c.peek=function(){return d};c.valueHasMutated=function(){c.notifySubscribers(d)};c.valueChange=function(a){c.notifySubscribers(a,"changing")};c.valueWillMutate=function(){c.notifySubscribers(d,
"beforeChange")};a.exportProperty(c,"peek",c.peek);a.exportProperty(c,"valueHasMutated",c.valueHasMutated);a.exportProperty(c,"valueChange",c.valueChange);a.exportProperty(c,"valueWillMutate",c.valueWillMutate);return c};a.observable2.fn={equalityComparer:L};var J=a.observable2.protoProperty="__ko_proto__";a.observable2.fn[J]=a.observable2;a.utils.canSetPrototype&&a.utils.setPrototypeOf(a.observable2.fn,a.subscribable.fn);a.hasPrototype=function(b,c){return null===b||b===q||b[J]===q?!1:b[J]===c?!0:
a.hasPrototype(b[J],c)};a.isObservable=function(a){return a instanceof F};a.isObservable2=function(b){return a.hasPrototype(b,a.observable2)};a.isWriteableObservable=function(a){return a instanceof I||a instanceof M&&a.hasWriteFunction?!0:!1};a.isWriteableObservable2=function(b){return"function"==typeof b&&b[J]===a.observable2||"function"==typeof b&&b[J]===a.dependentObservable2&&b.hasWriteFunction?!0:!1};a.exportSymbol("observable",a.observable);a.exportSymbol("isObservable",a.isObservable);a.exportSymbol("isWriteableObservable",
a.isWriteableObservable);a.exportSymbol("isWritableObservable",a.isWriteableObservable);var K=function(a){a=a||[];if("object"!=typeof a||!("length"in a))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");I.call(this,a);this.extend({trackArrayChanges:!0})};K.prototype=B(I);a.utils.extend(K.prototype,{remove:function(b){for(var c=this.peek(),d=[],e="function"!=typeof b||a.isObservable2(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var h=
c[f];e(h)&&(0===d.length&&this.valueWillMutate(),d.push(h),c.splice(f,1),f--)}d.length&&this.valueHasMutated();return d},removeAll:function(b){if(b===q){var c=this.peek(),d=c.slice(0);this.valueWillMutate();c.splice(0,c.length);this.valueHasMutated();return d}return b?this.remove(function(c){return 0<=a.utils.arrayIndexOf(b,c)}):[]},destroy:function(b){var c=this.peek(),d="function"!=typeof b||a.isObservable2(b)?function(a){return a===b}:b;this.valueWillMutate();for(var e=c.length-1;0<=e;e--)d(c[e])&&
(c[e]._destroy=!0);this.valueHasMutated()},destroyAll:function(b){return b===q?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=a.utils.arrayIndexOf(b,c)}):[]},indexOf:function(b){var c=this.get();return a.utils.arrayIndexOf(c,b)},replace:function(a,c){var d=this.indexOf(a);0<=d&&(this.valueWillMutate(),this.peek()[d]=c,this.valueHasMutated())}});a.utils.arrayForEach("pop push reverse shift sort splice unshift".split(" "),function(a){K.prototype[a]=function(){var c=this.peek();
this.valueWillMutate();this.cacheDiffForKnownOperation(c,a,arguments);c=c[a].apply(c,arguments);this.valueHasMutated();return c}});a.utils.arrayForEach(["slice"],function(a){K.prototype[a]=function(){var c=this.get();return c[a].apply(c,arguments)}});a.observableArray=function(a){return new K(a)};a.isObservableArray=function(a){return a instanceof K};a.observableArray2=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");
b=a.observable2(b);a.utils.setPrototypeOfOrExtend(b,a.observableArray2.fn);return b.extend({trackArrayChanges:!0})};a.observableArray2.fn={remove:function(b){for(var c=this.peek(),d=[],e="function"!=typeof b||a.isObservable2(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var h=c[f];e(h)&&(0===d.length&&this.valueWillMutate(),d.push(h),c.splice(f,1),f--)}d.length&&this.valueHasMutated();return d},removeAll:function(b){if(b===q){var c=this.peek(),d=c.slice(0);this.valueWillMutate();c.splice(0,c.length);
this.valueHasMutated();return d}return b?this.remove(function(c){return 0<=a.utils.arrayIndexOf(b,c)}):[]},destroy:function(b){var c=this.peek(),d="function"!=typeof b||a.isObservable2(b)?function(a){return a===b}:b;this.valueWillMutate();for(var e=c.length-1;0<=e;e--)d(c[e])&&(c[e]._destroy=!0);this.valueHasMutated()},destroyAll:function(b){return b===q?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=a.utils.arrayIndexOf(b,c)}):[]},indexOf:function(b){var c=this();return a.utils.arrayIndexOf(c,
b)},replace:function(a,c){var d=this.indexOf(a);0<=d&&(this.valueWillMutate(),this.peek()[d]=c,this.valueHasMutated())}};a.utils.arrayForEach("pop push reverse shift sort splice unshift".split(" "),function(b){a.observableArray2.fn[b]=function(){var a=this.peek();this.valueWillMutate();this.cacheDiffForKnownOperation(a,b,arguments);a=a[b].apply(a,arguments);this.valueHasMutated();return a}});a.utils.arrayForEach(["slice"],function(b){a.observableArray2.fn[b]=function(){var a=this();return a[b].apply(a,
arguments)}});a.utils.canSetPrototype&&a.utils.setPrototypeOf(a.observableArray2.fn,a.observable2.fn);a.exportSymbol("observableArray",a.observableArray);a.exportSymbol("isObservableArray",a.isObservableArray);a.extenders.trackArrayChanges=function(b){function c(){if(!d){d=!0;var c=b.notifySubscribers;b.notifySubscribers=function(a,b){b&&"change"!==b||++f;return c.apply(this,arguments)};var g=[].concat(b.peek()||[]);e=null;b.subscribe(function(c){c=[].concat(c||[]);if(b.hasSubscriptionsForEvent("arrayChange")){var d;
if(!e||1<f)e=a.utils.compareArrays(g,c,{sparse:!0});d=e;d.length&&b.notifySubscribers(d,"arrayChange")}g=c;e=null;f=0})}}if(!b.cacheDiffForKnownOperation){var d=!1,e=null,f=0,h=b.subscribe;b.subscribe=b.subscribe=function(a,b,d){"arrayChange"===d&&c();return h.apply(this,arguments)};b.cacheDiffForKnownOperation=function(b,c,l){function m(a,b,c){return h[h.length]={status:a,value:b,index:c}}if(d&&!f){var h=[],n=b.length,p=l.length,s=0;switch(c){case "push":s=n;case "unshift":for(c=0;c<p;c++)m("added",
l[c],s+c);break;case "pop":s=n-1;case "shift":n&&m("deleted",b[s],s);break;case "splice":c=Math.min(Math.max(0,0>l[0]?n+l[0]:l[0]),n);for(var n=1===p?n:Math.min(c+(l[1]||0),n),p=c+p-2,s=Math.max(n,p),z=[],u=[],H=2;c<s;++c,++H)c<n&&u.push(m("deleted",b[c],c)),c<p&&z.push(m("added",l[H],c));a.utils.findMovesInArrayComparison(u,z);break;default:return}e=h}}}};var M=function(b,c,d){this.latestValue=null;this.needsEvaluation=!0;this.isDisposed=this.suppressDisposalUntilDisposeWhenReturnsFalse=this.isBeingEvaluated=
!1;this.readFunction=b;this.isSleeping=this.pure=!1;this.readFunction&&"object"==typeof this.readFunction?(d=this.readFunction,this.readFunction=d.read):(d=d||{},this.readFunction||(this.readFunction=d.read));if("function"!=typeof this.readFunction)throw Error("Pass a function that returns the value of the ko.computed");this.writeFunction=d.write;this.disposeWhenNodeIsRemoved=d.disposeWhenNodeIsRemoved||d.disposeWhenNodeIsRemoved||null;this.disposeWhen=this.disposeWhenOption=d.disposeWhen||d.disposeWhen;
this.dispose=this.disposeComputed;this.subscriptionsToDependencies={};this.dependenciesCount=0;this.evaluationTimeoutInstance=null;this.evaluatorFunctionTarget=c||d.owner;this.hasWriteFunction="function"===typeof d.write;this._subscriptions={};var e=this;this.limit=function(a){limit.call(this,a);this.evalRateLimited=function(){this.rateLimitedBeforeChange(this.latestValue);this.needsEvaluation=!0;this.rateLimitedChange(this)}};d.pure?(this.isSleeping=this.pure=!0,this.beforeSubscriptionAdd=function(){e.isSleeping&&
(e.isSleeping=!1,e.evaluateImmediate(!0))},this.afterSubscriptionRemove=function(){e.getSubscriptionsCount()||(e.disposeAllSubscriptionsToDependencies(),e.isSleeping=e.needsEvaluation=!0)}):d.deferEvaluation&&(this.beforeSubscriptionAdd=function(){e.peek();delete e.beforeSubscriptionAdd});this.disposeWhenNodeIsRemoved&&(this.suppressDisposalUntilDisposeWhenReturnsFalse=!0,this.disposeWhenNodeIsRemoved.nodeType&&(this.disposeWhen=function(){return!a.utils.domNodeIsAttachedToDocument(this.disposeWhenNodeIsRemoved)||
this.disposeWhenOption&&this.disposeWhenOption()}));this.isSleeping||d.deferEvaluation||this.evaluateImmediate();this.disposeWhenNodeIsRemoved&&this.isActive()&&this.disposeWhenNodeIsRemoved.nodeType&&(this.dispose=function(){a.utils.domNodeDisposal.removeDisposeCallback(e.disposeWhenNodeIsRemoved,e.dispose);e.disposeComputed()},a.utils.domNodeDisposal.addDisposeCallback(this.disposeWhenNodeIsRemoved,this.dispose))};M.prototype=B(F);a.utils.extend(M.prototype,{addSubscriptionToDependency:function(a,
c){var d=this;this.subscriptionsToDependencies[c]||(this.subscriptionsToDependencies[c]=a.subscribe(function(){d.evaluatePossiblyAsync()}),++this.dependenciesCount)},disposeAllSubscriptionsToDependencies:function(){a.utils.objectForEach(this.subscriptionsToDependencies,function(a,c){c.dispose()});this.subscriptionsToDependencies={}},disposeComputed:function(){this.disposeAllSubscriptionsToDependencies();this.dependenciesCount=0;this.isDisposed=!0;this.needsEvaluation=!1},evaluatePossiblyAsync:function(){var a=
this.throttleEvaluation;a&&0<=a?(clearTimeout(this.evaluationTimeoutInstance),this.evaluationTimeoutInstance=setTimeout(this.evaluateImmediate,a)):this.evalRateLimited?this.evalRateLimited():this.evaluateImmediate()},evaluateImmediate:function(b){var c=this;if(this.isBeingEvaluated){if(this.pure)throw Error("A 'pure' computed must not be called recursively");}else if(!this.isDisposed){if(this.disposeWhen&&this.disposeWhen()){if(!this.suppressDisposalUntilDisposeWhenReturnsFalse){this.dispose();return}}else this.suppressDisposalUntilDisposeWhenReturnsFalse=
!1;this.isBeingEvaluated=!0;if(this.isSleeping)try{var d={};a.dependencyDetection.begin({callback:function(a,b){d[b]||(d[b]=1,++c.dependenciesCount)},computed:this,isInitial:q});this.dependenciesCount=0;this.latestValue=this.readFunction.call(this.evaluatorFunctionTarget)}finally{a.dependencyDetection.end(),this.isBeingEvaluated=!1}else try{var e=this.subscriptionsToDependencies,f=this.dependenciesCount,c=this;a.dependencyDetection.begin({callback:function(a,b){c.isDisposed||(f&&e[b]?(c.subscriptionsToDependencies[b]=
e[b],++c.dependenciesCount,delete e[b],--f):c.addSubscriptionToDependency(a,b))},computed:this,isInitial:this.pure?q:!this.dependenciesCount});this.subscriptionsToDependencies={};this.dependenciesCount=0;try{var h=this.evaluatorFunctionTarget?this.readFunction.call(this.evaluatorFunctionTarget):this.readFunction()}finally{a.dependencyDetection.end(),f&&a.utils.objectForEach(e,function(a,b){b.dispose()}),this.needsEvaluation=!1}this.isDifferent(this.latestValue,h)&&(this.notifySubscribers(this.latestValue,
"beforeChange"),this.latestValue=h,!0!==b&&this.notifySubscribers(this.latestValue))}finally{this.isBeingEvaluated=!1}this.dependenciesCount||this.dispose()}},set:function(){if("function"===typeof this.writeFunction)this.writeFunction.apply(this.evaluatorFunctionTarget,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this},get:function(){a.dependencyDetection.registerDependency(this);
this.needsEvaluation&&this.evaluateImmediate(!0);return this.latestValue},peek:function(){this.needsEvaluation&&!this.dependenciesCount&&this.evaluateImmediate(!0);return this.latestValue},isActive:function(){return this.needsEvaluation||0<this.dependenciesCount},getDependenciesCount:function(){return this.dependenciesCount},equalityComparer:L});a.computed=a.dependentObservable=function(a,c,d){return new M(a,c,d)};a.dependentObservable2=function(b,c,d){function e(){a.utils.objectForEach(E,function(a,
b){b.dispose()});E={}}function f(){e();C=0;z=!0;n=!1}function h(){var a=g.throttleEvaluation;a&&0<=a?(clearTimeout(w),w=setTimeout(k,a)):g._evalRateLimited?g._evalRateLimited():k()}function k(b){if(p){if(H)throw Error("A 'pure' computed must not be called recursively");}else if(!z){if(t&&t()){if(!s){D();return}}else s=!1;p=!0;if(A)try{var d={};a.dependencyDetection.begin({callback:function(a,b){d[b]||(d[b]=1,++C)},computed:g,isInitial:q});C=0;r=u.call(c)}finally{a.dependencyDetection.end(),p=!1}else try{var e=
E,l=C;a.dependencyDetection.begin({callback:function(a,b){z||(l&&e[b]?(E[b]=e[b],++C,delete e[b],--l):E[b]||(E[b]=a.subscribe(h),++C))},computed:g,isInitial:H?q:!C});E={};C=0;try{var m=c?u.call(c):u()}finally{a.dependencyDetection.end(),l&&a.utils.objectForEach(e,function(a,b){b.dispose()}),n=!1}g.isDifferent(r,m)&&(g.notifySubscribers(r,"beforeChange"),r=m,DEBUG&&(g._latestValue=r),!0!==b&&g.notifySubscribers(r))}finally{p=!1}C||D()}}function g(){if(0<arguments.length){if("function"===typeof x)x.apply(c,
arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}a.dependencyDetection.registerDependency(g);n&&k(!0);return r}function l(){n&&!C&&k(!0);return r}function m(){return n||0<C}var r,n=!0,p=!1,s=!1,z=!1,u=b,H=!1,A=!1;u&&"object"==typeof u?(d=u,u=d.read):(d=d||{},u||(u=d.read));if("function"!=typeof u)throw Error("Pass a function that returns the value of the ko.computed");
var x=d.write,v=d.disposeWhenNodeIsRemoved||d.disposeWhenNodeIsRemoved||null,O=d.disposeWhen||d.disposeWhen,t=O,D=f,E={},C=0,w=null;c||(c=d.owner);a.subscribable.call(g);a.utils.setPrototypeOfOrExtend(g,a.dependentObservable2.fn);g.peek=l;g.getDependenciesCount=function(){return C};g.hasWriteFunction="function"===typeof d.write;g.dispose=function(){D()};g.isActive=m;var X=g.limit;g.limit=function(a){X.call(g,a);g._evalRateLimited=function(){g._rateLimitedBeforeChange(r);n=!0;g._rateLimitedChange(g)}};
d.pure?(A=H=!0,g.beforeSubscriptionAdd=function(){A&&(A=!1,k(!0))},g.afterSubscriptionRemove=function(){g.getSubscriptionsCount()||(e(),A=n=!0)}):d.deferEvaluation&&(g.beforeSubscriptionAdd=function(){l();delete g.beforeSubscriptionAdd});a.exportProperty(g,"peek",g.peek);a.exportProperty(g,"dispose",g.dispose);a.exportProperty(g,"isActive",g.isActive);a.exportProperty(g,"getDependenciesCount",g.getDependenciesCount);v&&(s=!0,v.nodeType&&(t=function(){return!a.utils.domNodeIsAttachedToDocument(v)||
O&&O()}));A||d.deferEvaluation||k();v&&m()&&v.nodeType&&(D=function(){a.utils.domNodeDisposal.removeDisposeCallback(v,D);f()},a.utils.domNodeDisposal.addDisposeCallback(v,D));return g};a.isComputed=function(b){return a.hasPrototype(b,a.dependentObservable2)};B=a.observable2.protoProperty;a.dependentObservable2[B]=a.observable2;a.dependentObservable2.fn={equalityComparer:L};a.dependentObservable2.fn[B]=a.dependentObservable2;a.utils.canSetPrototype&&a.utils.setPrototypeOf(a.dependentObservable2.fn,
a.subscribable.fn);a.exportSymbol("dependentObservable",a.dependentObservable);a.exportSymbol("computed",a.dependentObservable);a.exportSymbol("isComputed",a.isComputed);a.pureComputed=function(b,c){if("function"===typeof b)return a.computed(b,c,{pure:!0});b=a.utils.extend({},b);b.pure=!0;return a.computed(b,c)};a.exportSymbol("pureComputed",a.pureComputed);(function(){function b(a,f,h){h=h||new d;a=f(a);if("object"!=typeof a||null===a||a===q||a instanceof Date||a instanceof String||a instanceof Number||
a instanceof Boolean)return a;var k=a instanceof Array?[]:{};h.save(a,k);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":k[c]=d;break;case "object":case "undefined":var m=h.get(d);k[c]=m!==q?m:b(d,f,h)}});return k}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.values=[]}a.toJS=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");
return b(c,function(b){for(var c=0;(a.isObservable2(b)||b instanceof F)&&10>c;c++)b=b instanceof F?b.get():b();return b})};a.toJSON=function(b,c,d){b=a.toJS(b);return a.utils.stringifyJson(b,c,d)};d.prototype={constructor:d,save:function(b,c){var d=a.utils.arrayIndexOf(this.keys,b);0<=d?this.values[d]=c:(this.keys.push(b),this.values.push(c))},get:function(b){b=a.utils.arrayIndexOf(this.keys,b);return 0<=b?this.values[b]:q}}})();a.exportSymbol("toJS",a.toJS);a.exportSymbol("toJSON",a.toJSON);(function(){a.selectExtensions=
{readValue:function(b){switch(a.utils.tagNameLower(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.utils.domData.get(b,a.bindingHandlers.options.optionValueDomDataKey):7>=a.utils.ieVersion?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.selectExtensions.readValue(b.options[b.selectedIndex]):q;default:return b.value}},writeValue:function(b,c,d){switch(a.utils.tagNameLower(b)){case "option":switch(typeof c){case "string":a.utils.domData.set(b,
a.bindingHandlers.options.optionValueDomDataKey,q);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=c;break;default:a.utils.domData.set(b,a.bindingHandlers.options.optionValueDomDataKey,c),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof c?c:""}break;case "select":if(""===c||null===c)c=q;for(var e=-1,f=0,h=b.options.length,k;f<h;++f)if(k=a.selectExtensions.readValue(b.options[f]),k==c||""==k&&c===q){e=f;break}if(d||0<=e||c===q&&1<b.size)b.selectedIndex=
e;break;default:if(null===c||c===q)c="";b.value=c}}}})();a.exportSymbol("selectExtensions",a.selectExtensions);a.exportSymbol("selectExtensions.readValue",a.selectExtensions.readValue);a.exportSymbol("selectExtensions.writeValue",a.selectExtensions.writeValue);a.expressionRewriting=function(){function b(b){b=a.utils.stringTrim(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));var c=[],d=b.match(e),r,n,k=0;if(d){d.push(",");for(var s=0,z;z=d[s];++s){var u=z.charCodeAt(0);if(44===u){if(0>=k){r&&c.push(n?
{key:r,value:n.join("")}:{unknown:r});r=n=k=0;continue}}else if(58===u){if(!n)continue}else if(47===u&&s&&1<z.length)(u=d[s-1].match(f))&&!h[u[0]]&&(b=b.substr(b.indexOf(z)+1),d=b.match(e),d.push(","),s=-1,z="/");else if(40===u||123===u||91===u)++k;else if(41===u||125===u||93===u)--k;else if(!r&&!n){r=34===u||39===u?z.slice(1,-1):z;continue}n?n.push(z):n=[z]}}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:[^\"\\\\]|\\\\.)*\"|'(?:[^'\\\\]|\\\\.)*'|/(?:[^/\\\\]|\\\\.)*/w*|[^\\s:,/][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]]|[^\\s]",
"g"),f=/[\])"'A-Za-z0-9_$]+$/,h={"in":1,"return":1,"typeof":1},k={};return{bindingRewriteValidators:[],twoWayBindings:k,parseObjectLiteral:b,preProcessBindings:function(g,e){function m(b,g){var e;if(!s){var l=a.getBindingHandler(b);if(l&&l.preprocess&&!(g=l.preprocess(g,b,m)))return;if(l=k[b])e=g,0<=a.utils.arrayIndexOf(c,e)?e=!1:(l=e.match(d),e=null===l?!1:l[1]?"Object("+l[1]+")"+l[2]:e),l=e;l&&h.push("'"+b+"':function(_z){"+e+"=_z}")}p&&(g="function(){return "+g+" }");f.push("'"+b+"':"+g)}e=e||
{};var f=[],h=[],p=e.valueAccessors,s=e.bindingParams,z="string"===typeof g?b(g):g;a.utils.arrayForEach(z,function(a){m(a.key||a.unknown,a.value)});h.length&&m("_ko_property_writers","{"+h.join(",")+" }");return f.join(",")},keyValueArrayContainsKey:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},writeValueToProperty:function(b,c,d,e,f){if(a.isWriteableObservable(b))b.set(e);else if(b&&a.isObservable2(b))!a.isWriteableObservable2(b)||f&&b.peek()===e||b(e);else if((b=c.get("_ko_property_writers"))&&
b[d])b[d](e)}}}();a.exportSymbol("expressionRewriting",a.expressionRewriting);a.exportSymbol("expressionRewriting.bindingRewriteValidators",a.expressionRewriting.bindingRewriteValidators);a.exportSymbol("expressionRewriting.parseObjectLiteral",a.expressionRewriting.parseObjectLiteral);a.exportSymbol("expressionRewriting.preProcessBindings",a.expressionRewriting.preProcessBindings);a.exportSymbol("expressionRewriting._twoWayBindings",a.expressionRewriting.twoWayBindings);a.exportSymbol("jsonExpressionRewriting",
a.expressionRewriting);a.exportSymbol("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.expressionRewriting.preProcessBindings);(function(){function b(a){return 8==a.nodeType&&h.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&k.test(f?a.text:a.nodeValue)}function d(a,d){for(var g=a,e=1,f=[];g=g.nextSibling;){if(c(g)&&(e--,0===e))return f;f.push(g);b(g)&&e++}if(!d)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,b){var c=d(a,b);
return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:null}var f=y&&"\x3c!--test--\x3e"===y.createComment("test").text,h=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,k=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,g={ul:!0,ol:!0};a.virtualElements={allowedBindings:{},childNodes:function(a){return b(a)?d(a):a.childNodes},emptyNode:function(c){if(b(c)){c=a.virtualElements.childNodes(c);for(var d=0,g=c.length;d<g;d++)a.removeNode(c[d])}else a.utils.emptyDomNode(c)},
setDomNodeChildren:function(c,d){if(b(c)){a.virtualElements.emptyNode(c);for(var g=c.nextSibling,e=0,f=d.length;e<f;e++)g.parentNode.insertBefore(d[e],g)}else a.utils.setDomNodeChildren(c,d)},prepend:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},insertAfter:function(c,d,g){g?b(c)?c.parentNode.insertBefore(d,g.nextSibling):g.nextSibling?c.insertBefore(d,g.nextSibling):c.appendChild(d):a.virtualElements.prepend(c,d)},firstChild:function(a){return b(a)?
!a.nextSibling||c(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));return a.nextSibling&&c(a.nextSibling)?null:a.nextSibling},hasBindingValue:b,virtualNodeBindingValue:function(a){return(a=(f?a.text:a.nodeValue).match(h))?a[1]:null},normaliseVirtualElementDomStructure:function(d){if(g[a.utils.tagNameLower(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var h;h=f.firstChild;var k=null;if(h){do if(k)k.push(h);else if(b(h)){var p=e(h,!0);p?h=p:k=[h]}else c(h)&&
(k=[h]);while(h=h.nextSibling)}if(h=k)for(k=f.nextSibling,p=0;p<h.length;p++)k?d.insertBefore(h[p],k):d.appendChild(h[p])}while(f=f.nextSibling)}}}}})();a.exportSymbol("virtualElements",a.virtualElements);a.exportSymbol("virtualElements.allowedBindings",a.virtualElements.allowedBindings);a.exportSymbol("virtualElements.emptyNode",a.virtualElements.emptyNode);a.exportSymbol("virtualElements.insertAfter",a.virtualElements.insertAfter);a.exportSymbol("virtualElements.prepend",a.virtualElements.prepend);
a.exportSymbol("virtualElements.setDomNodeChildren",a.virtualElements.setDomNodeChildren);(function(){a.bindingProvider=function(){this.bindingCache={}};a.utils.extend(a.bindingProvider.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.components.getComponentNameForNode(b);case 8:return a.virtualElements.hasBindingValue(b);default:return!1}},getBindings:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,c,b):null;
return a.components.addBindingsForCustomElement(d,b,c,!1)},getBindingAccessors:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,c,b,{valueAccessors:!0}):null;return a.components.addBindingsForCustomElement(d,b,c,!0)},getBindingsString:function(b,c){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.virtualElements.virtualNodeBindingValue(b);default:return null}},parseBindingsString:function(b,c,d,e){try{var f=this.bindingCache,h=b+(e&&e.valueAccessors||
""),k;if(!(k=f[h])){var g,l="with($context){with($object||{}){return{"+a.expressionRewriting.preProcessBindings(b,e)+"}}}";g=new Function("$context","$element",l);k=f[h]=g}return k(c,d)}catch(m){throw m.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+m.message,m;}}});a.bindingProvider.instance=new a.bindingProvider})();a.exportSymbol("bindingProvider",a.bindingProvider);(function(){function b(a){return function(){return a}}function c(a){return a()}function d(b){return a.utils.objectMap(a.dependencyDetection.ignore(b),
function(a,c){return function(){return b()[c]}})}function e(c,g,e){return"function"===typeof c?d(c.bind(null,g,e)):a.utils.objectMap(c,b)}function f(a,b){return d(this.getBindings.bind(this,a,b))}function h(b,c,d){var g,e=a.virtualElements.firstChild(c),f=a.bindingProvider.instance,l=f.preprocessNode;if(l){for(;g=e;)e=a.virtualElements.nextSibling(g),l.call(f,g);e=a.virtualElements.firstChild(c)}for(;g=e;)e=a.virtualElements.nextSibling(g),k(b,g,d)}function k(b,c,d){var g=!0;if(1===c.nodeType&&!c.getAttribute("id")){var e=
c.getAttribute("xid");e&&c.setAttribute("id",b.$model.getContextID()+"_"+e)}1===c.nodeType&&a.utils.domData.set(c,n,!0);(e=1===c.nodeType)&&a.virtualElements.normaliseVirtualElementDomStructure(c);if(e&&d||a.bindingProvider.instance.nodeHasBindings(c))g=l(c,null,b,d).shouldBindDescendants;g&&!r[a.utils.tagNameLower(c)]&&h(b,c,!e);if(1===c.nodeType&&(b=a.utils.domNodeReady.getReadyCallbacks(c,!1)))for(b=b.slice(0),d=0;d<b.length;d++)b[d](c)}function g(b){var c=[],d={},g=[];a.utils.objectForEach(b,
function v(e){if(!d[e]){var f=a.getBindingHandler(e);f&&(f.after&&(g.push(e),a.utils.arrayForEach(f.after,function(c){if(b[c]){if(-1!==a.utils.arrayIndexOf(g,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+g.join(", "));v(c)}}),g.length--),c.push({key:e,handler:f}));d[e]=!0}});return c}function l(b,d,e,l){var m=a.utils.domData.get(b,p);if(!d){if(m)throw Error("You cannot apply bindings multiple times to the same element.");a.utils.domData.set(b,p,!0)}!m&&
l&&a.storedBindingContextForNode(b,e);var h;if(d&&"function"!==typeof d)h=d;else{var k=a.bindingProvider.instance,n=k.getBindingAccessors||f,r=a.dependentObservable(function(){(h=d?d(e,b):n.call(k,b,e))&&e._subscribable&&e._subscribable();return h},null,{disposeWhenNodeIsRemoved:b});h&&r.isActive()||(r=null)}var s;if(h){var t=r?function(a){return function(){return c(r()[a])}}:function(a){return h[a]},w=function(){return a.utils.objectMap(r?r():h,c)};w.get=function(a){return h[a]&&c(t(a))};w.has=function(a){return a in
h};l=g(h);a.utils.arrayForEach(l,function(c){var d=c.handler.init,g=c.handler.update,f=c.key;if(8===b.nodeType&&!a.virtualElements.allowedBindings[f])throw Error("The binding '"+f+"' cannot be used with virtual elements");try{"function"==typeof d&&a.dependencyDetection.ignore(function(){var a=d(b,t(f),w,e.$object,e);if(a&&a.controlsDescendantBindings){if(s!==q)throw Error("Multiple bindings ("+s+" and "+f+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");
s=f}}),"function"==typeof g&&a.dependentObservable(function(){g(b,t(f),w,e.$object,e)},null,{disposeWhenNodeIsRemoved:b})}catch(l){throw l.message='Unable to process binding "'+f+": "+h[f]+'"\nMessage: '+l.message,l;}})}return{shouldBindDescendants:s===q}}function m(b){return b&&b instanceof a.bindingContext?b:new a.bindingContext(b)}a.bindingHandlers={};var r={script:!0};a.getBindingHandler=function(b){return a.bindingHandlers[b]};a.bindingContext=function(b,c,d,g){var e=this,f="function"==typeof b&&
!a.isObservable2(b),l,m=a.dependentObservable(function(){var l=f?b():b,h=a.utils.unwrapObservable(l);c?(c._subscribable&&c._subscribable(),a.utils.extend(e,c),m&&(e._subscribable=m)):(e.$parents=[],e.$model=h,e.ko=a);e.$rawData=l;e.$object=h;d&&(e[d]=h);g&&g(e,c,h);return e.$object},null,{disposeWhen:function(){return l&&!a.utils.anyDomNodeIsAttachedToDocument(l)},disposeWhenNodeIsRemoved:!0});m.isActive()&&(e._subscribable=m,m.equalityComparer=null,l=[],m._addNode=function(b){l.push(b);a.utils.domNodeDisposal.addDisposeCallback(b,
function(b){a.utils.arrayRemoveItem(l,b);l.length||(m.dispose(),e._subscribable=m=q)})})};a.bindingContext.prototype.createChildContext=function(b,c,d){return new a.bindingContext(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$object;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)})};a.bindingContext.prototype.extend=function(b){return new a.bindingContext(this._subscribable||this.$object,this,null,function(c,d){c.$rawData=d.$rawData;a.utils.extend(c,"function"==
typeof b?b():b)})};var n="__boundElementKey__",p=a.utils.domData.nextKey(),s=a.utils.domData.nextKey();a.storedBindingContextForNode=function(b,c){if(2==arguments.length)a.utils.domData.set(b,s,c),c._subscribable&&c._subscribable._addNode(b);else return a.utils.domData.get(b,s)};a.applyBindingAccessorsToNode=function(b,c,d){1===b.nodeType&&a.virtualElements.normaliseVirtualElementDomStructure(b);return l(b,c,m(d),!0)};a.applyBindingsToNode=function(b,c,d){d=m(d);return a.applyBindingAccessorsToNode(b,
e(c,d,b),d)};a.applyBindingsToDescendants=function(a,b){1!==b.nodeType&&8!==b.nodeType||h(m(a),b,!0)};a.applyBindings=function(a,b){!t&&w.jQuery&&(t=w.jQuery);if(b&&1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");b=b||w.document.body;k(m(a),b,!0)};a.isBound=function(b){return a.utils.domData.get(b,n)};a.addNodes=function(b,c,d){if(!b)throw Error("\u6dfb\u52a0\u5b50\u8282\u70b9\u65f6\uff0c\u7236\u8282\u70b9\u4e0d\u5141\u8bb8\u4e3a\u7a7a");
if(c){var g=$(b);b=a.isBound(b);for(var e=0;e<c.length;e++){var f=c[e];if(f&&(d&&d.nodeType?$(d).before(f):g.append(f),b)){var l=a.contextFor(f);a.applyBindings(l,f)}}}};a.addNode=function(b,c,d){a.addNodes(b,[c],d)};a.addComponents=function(b,c,d){if(c){for(var e=[],g=0;g<c.length;g++){var f=c[g];f.domNode&&(e[e.length]=f.domNode)}a.addNodes(b,e,d)}};a.addComponent=function(b,c,d){a.addComponents(b,[c],d)};a.addComponentsOrNodes=function(b,c,d){if(components){for(var e=[],g=0;g<c.length;g++){var f=
c[g];f&&(f.nodeType?e[e.length]=f:f.domNode&&(e[e.length]=f.domNode))}a.addNodes(b,e,d)}};a.addComponentOrElement=function(b,c,d){a.addComponentsOrNodes(b,[c],d)};a.contextFor=function(b){switch(b.nodeType){case 1:case 8:var c=a.storedBindingContextForNode(b);if(c)return c;if(b.parentNode)return a.contextFor(b.parentNode)}return q};a.dataFor=function(b){return(b=a.contextFor(b))?b.$object:q};a.exportSymbol("bindingHandlers",a.bindingHandlers);a.exportSymbol("applyBindings",a.applyBindings);a.exportSymbol("applyBindingsToDescendants",
a.applyBindingsToDescendants);a.exportSymbol("applyBindingAccessorsToNode",a.applyBindingAccessorsToNode);a.exportSymbol("applyBindingsToNode",a.applyBindingsToNode);a.exportSymbol("contextFor",a.contextFor);a.exportSymbol("dataFor",a.dataFor);a.exportSymbol("addNodes",a.addNodes);a.exportSymbol("addNode",a.addNode);a.exportSymbol("addComponents",a.addComponents);a.exportSymbol("addComponent",a.addComponent);a.exportSymbol("addComponentsOrNodes",a.addComponentsOrNodes);a.exportSymbol("addComponentOrNode",
a.addComponentOrNode);a.exportSymbol("isBound",a.isBound)})();(function(b){function c(a,c){return a.hasOwnProperty(c)?a[c]:b}function d(b,d){var f=c(h,b),r;f||(f=h[b]=new a.subscribable,e(b,function(a){k[b]=a;delete h[b];r?f.notifySubscribers(a):setTimeout(function(){f.notifySubscribers(a)},0)}),r=!0);f.subscribe(d)}function e(a,b){f("getConfig",[a],function(c){c?f("loadComponent",[a,c],function(a){b(a)}):b(null)})}function f(c,d,e,h){h||(h=a.components.loaders.slice(0));var k=h.shift();if(k){var p=
k[c];if(p){var s=!1;if(p.apply(k,d.concat(function(a){s?e(null):null!==a?e(a):f(c,d,e,h)}))!==b&&(s=!0,!k.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else f(c,d,e,h)}else e(null)}var h={},k={};a.components={get:function(a,b){var e=c(k,a);e?setTimeout(function(){b(e)},0):d(a,b)},clearCachedDefinition:function(a){delete k[a]},_getFirstResultFromLoaders:f};a.components.loaders=[];a.exportSymbol("components",
a.components);a.exportSymbol("components.get",a.components.get);a.exportSymbol("components.clearCachedDefinition",a.components.clearCachedDefinition)})();(function(b){function c(b,c,d,f){var h={},p=2,s=function(){0===--p&&f(h)},z=d.template;d=d.viewModel;z?e(c,z,function(c){a.components._getFirstResultFromLoaders("loadTemplate",[b,c],function(a){h.template=a;s()})}):s();d?e(c,d,function(c){a.components._getFirstResultFromLoaders("loadViewModel",[b,c],function(a){h[k]=a;s()})}):s()}function d(a,b,
c){if("function"===typeof b)c(function(a){return new b(a)});else if("function"===typeof b[k])c(b[k]);else if("instance"in b){var e=b.instance;c(function(a,b){return e})}else"viewModel"in b?d(a,b.viewModel,c):a("Unknown viewModel value: "+b)}function e(a,b,c){"string"===typeof b.require?S||w.require?(S||w.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function f(a){return function(b){throw Error("Component '"+a+"': "+b);}}var h={};a.components.register=function(b,c){if(!c)throw Error("Invalid configuration for "+
b);if(a.components.isRegistered(b))throw Error("Component "+b+" is already registered");h[b]=c};a.components.isRegistered=function(a){return a in h};a.components.unregister=function(b){delete h[b];a.components.clearCachedDefinition(b)};a.components.defaultLoader={getConfig:function(a,b){var c=h.hasOwnProperty(a)?h[a]:null;b(c)},loadComponent:function(a,b,d){var h=f(a);e(h,b,function(b){c(a,h,b,d)})},loadTemplate:function(b,c,d){b=f(b);if("string"===typeof c)d(a.utils.parseHtmlFragment(c));else if(c instanceof
Array)d(c);else if(w.DocumentFragment?c instanceof DocumentFragment:c&&11===c.nodeType)d(a.utils.makeArray(c.childNodes));else if(c.element)if(c=c.element,w.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)d(cloneNodesFromTemplateSourceElement(c));else if("string"===typeof c){var e=y.getElementById(c);e?d(cloneNodesFromTemplateSourceElement(e)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,c){d(f(a),
b,c)}};var k="createViewModel";a.exportSymbol("components.register",a.components.register);a.exportSymbol("components.isRegistered",a.components.isRegistered);a.exportSymbol("components.unregister",a.components.unregister);a.exportSymbol("components.defaultLoader",a.components.defaultLoader);a.components.loaders.push(a.components.defaultLoader);a.components._allRegisteredComponents=h})();(function(b){function c(b,c){var h=b.getAttribute("params");if(h){var h=d.parseBindingsString(h,c,b,{valueAccessors:!0,
bindingParams:!0}),h=a.utils.objectMap(h,function(c,d){return a.computed(c,null,{disposeWhenNodeIsRemoved:b})}),k=a.utils.objectMap(h,function(c,d){return c.isActive()?a.computed(function(){return a.utils.unwrapObservable(c())},null,{disposeWhenNodeIsRemoved:b}):c.peek()});k.hasOwnProperty("$raw")||(k.$raw=h);return k}return{$raw:{}}}a.components.getComponentNameForNode=function(b){b=a.utils.tagNameLower(b);return a.components.isRegistered(b)&&b};a.components.addBindingsForCustomElement=function(b,
d,h,k){if(1===d.nodeType){var g=a.components.getComponentNameForNode(d);if(g){b=b||{};if(b.component)throw Error('Cannot use the "component" binding on a custom element matching a component');var l={name:g,params:c(d,h)};b.component=k?function(){return l}:l}}return b};var d=new a.bindingProvider;9>a.utils.ieVersion&&(a.components.register=function(a){return function(b){y.createElement(b);return a.apply(this,arguments)}}(a.components.register),y.createDocumentFragment=function(b){return function(){var c=
b(),d=a.components._allRegisteredComponents,k;for(k in d)d.hasOwnProperty(k)&&c.createElement(k);return c}}(y.createDocumentFragment))})();(function(b){var c=0;a.bindingHandlers.component={_init2:function(b,e,f,h,k){var g,l,m=function(){var a=g&&g.dispose;"function"===typeof a&&a.call(g);l=null};a.utils.domNodeDisposal.addDisposeCallback(b,m);a.computed(function(){var f=a.utils.unwrapObservable(e()),h,p;"string"===typeof f?h=f:(h=a.utils.unwrapObservable(f.name),p=a.utils.unwrapObservable(f.params));
if(!h)throw Error("No component name specified");var s=l=++c;a.components.get(h,function(c){if(l===s){m();if(!c)throw Error("Unknown component '"+h+"'");var e=c.template;if(!e)throw Error("Component '"+h+"' has no template");e=a.utils.cloneNodes(e);a.virtualElements.setDomNodeChildren(b,e);var e=p,f=c.createViewModel;c=f?f.call(c,e,{element:b}):e;e=k.createChildContext(c);g=c;a.applyBindingsToDescendants(e,b)}})},null,{disposeWhenNodeIsRemoved:b});return{controlsDescendantBindings:!0}},_init1:function(b,
c,f,h,k){c=a.utils.unwrapObservable(c());var g=c.name;if(g&&a.bindingHandlers.component[g])return a.bindingHandlers.component[g].init(b,c,f,h,k);throw Error("component '"+g+"' not found!");},_update1:function(b,c,f,h,k){c=a.utils.unwrapObservable(c());var g=c.name;if(g&&a.bindingHandlers.component[g])return a.bindingHandlers.component[g].update(b,c,f,h,k);throw Error("component '"+g+"' not found!");},_isComponent1:function(a){return a&&a.indexOf&&0===a.indexOf("$model/")},init:function(b,c,f,h,k){var g=
a.utils.unwrapObservable(c());return a.bindingHandlers.component._isComponent1(a.utils.unwrapObservable(g.name))?a.bindingHandlers.component._init1(b,c,f,h,k):a.bindingHandlers.component._init2(b,c,f,h,k)},update:function(b,c,f,h,k){var g=a.utils.unwrapObservable(c());a.bindingHandlers.component._isComponent1(a.utils.unwrapObservable(g.name))&&a.bindingHandlers.component._update1(b,c,f,h,k)}};a.virtualElements.allowedBindings.component=!0})();var T={"class":"className","for":"htmlFor"};a.bindingHandlers.attr=
{update:function(b,c,d){c=a.utils.unwrapObservable(c())||{};a.utils.objectForEach(c,function(c,d){d=a.utils.unwrapObservable(d);var h=!1===d||null===d||d===q;h&&b.removeAttribute(c);8>=a.utils.ieVersion&&c in T?(c=T[c],h?b.removeAttribute(c):b[c]=d):h||b.setAttribute(c,d.toString());"name"===c&&a.utils.setElementName(b,h?"":d.toString())})}};(function(){a.bindingHandlers.checked={after:["value","attr"],init:function(b,c,d){function e(){var e=b.checked,f=r?h.get():e;if(!a.computedContext.isInitial()&&
(!g||e)){var k=a.dependencyDetection.ignore(c);l?m!==f?(e&&(a.utils.addOrRemoveItem(k,f,!0),a.utils.addOrRemoveItem(k,m,!1)),m=f):a.utils.addOrRemoveItem(k,f,e):a.expressionRewriting.writeValueToProperty(k,d,"checked",f,!0)}}function f(){var d=a.utils.unwrapObservable(c());b.checked=l?0<=a.utils.arrayIndexOf(d,h.get()):k?d:h.get()===d}var h=a.pureComputed(function(){return d.has("checkedValue")?a.utils.unwrapObservable(d.get("checkedValue")):d.has("value")?a.utils.unwrapObservable(d.get("value")):
b.value}),k="checkbox"==b.type,g="radio"==b.type;if(k||g){var l=k&&a.utils.unwrapObservable(c())instanceof Array,m=l?h.get():q,r=g||l;g&&!b.name&&a.bindingHandlers.uniqueName.init(b,function(){return!0});a.computed(e,null,{disposeWhenNodeIsRemoved:b});a.utils.registerEventHandler(b,"click",e);a.computed(f,null,{disposeWhenNodeIsRemoved:b})}}};a.expressionRewriting.twoWayBindings.checked=!0;a.bindingHandlers.checkedValue={update:function(b,c){b.value=a.utils.unwrapObservable(c())}}})();a.bindingHandlers.css=
{update:function(b,c){var d=a.utils.unwrapObservable(c());"object"==typeof d?a.utils.objectForEach(d,function(c,d){d=a.utils.unwrapObservable(d);a.utils.toggleDomNodeCssClass(b,c,d)}):(d=String(d||""),a.utils.toggleDomNodeCssClass(b,b.__ko__cssValue,!1),b.__ko__cssValue=d,a.utils.toggleDomNodeCssClass(b,d,!0))}};a.bindingHandlers.enable={update:function(b,c){var d=a.utils.unwrapObservable(c());d&&b.disabled?(b.removeAttribute("disabled"),b.disabled=!1):d||b.disabled||(b.setAttribute("disabled","disabled"),
b.disabled=!0)}};a.bindingHandlers.disable={update:function(b,c){a.bindingHandlers.enable.update(b,function(){return!a.utils.unwrapObservable(c())})}};a.bindingHandlers.event={init:function(b,c,d,e,f){var h=c()||{};a.utils.objectForEach(h,function(h){"string"==typeof h&&a.utils.registerEventHandler(b,h,function(b){var l,m=c()[h];if(m){try{var r=a.utils.makeArray(arguments);e=f.$object;r.unshift(e);l=m.apply(e,r)}finally{!1===l&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(h+"Bubble")&&
(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.bindingHandlers.foreach={makeTemplateValueAccessor:function(b){return function(){var c=b(),d=a.utils.peekObservable(c),e=function(b,c){for(var e=a.utils.domData.nextKey(),g=0;g<b.length;g++){var l=b[g];l&&l.nodeType&&1==l.nodeType&&l.setAttribute("__inline-id__",e)}d&&d.afterRender&&d.afterRender(b,c)};if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.nativeTemplateEngine.instance,afterRender:e};a.utils.unwrapObservable(c);
return{foreach:d.data,as:d.as,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:e,beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.nativeTemplateEngine.instance}}},init:function(b,c,d,e,f){b.setAttribute("__component-context__","inline");return a.bindingHandlers.template.init(b,a.bindingHandlers.foreach.makeTemplateValueAccessor(c))},update:function(b,c,d,e,f){return a.bindingHandlers.template.update(b,a.bindingHandlers.foreach.makeTemplateValueAccessor(c),
d,e,f)}};a.expressionRewriting.bindingRewriteValidators.foreach=!1;a.virtualElements.allowedBindings.foreach=!0;a.bindingHandlers.hasfocus={init:function(b,c,d){var e=function(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if("activeElement"in f){var g;try{g=f.activeElement}catch(l){g=f.body}e=g===b}f=c();a.expressionRewriting.writeValueToProperty(f,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1},f=e.bind(null,!0),e=e.bind(null,!1);a.utils.registerEventHandler(b,"focus",
f);a.utils.registerEventHandler(b,"focusin",f);a.utils.registerEventHandler(b,"blur",e);a.utils.registerEventHandler(b,"focusout",e)},update:function(b,c){var d=!!a.utils.unwrapObservable(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===d||(d?b.focus():b.blur(),a.dependencyDetection.ignore(a.utils.triggerEvent,null,[b,d?"focusin":"focusout"]))}};a.expressionRewriting.twoWayBindings.hasfocus=!0;a.bindingHandlers.hasFocus=a.bindingHandlers.hasfocus;a.expressionRewriting.twoWayBindings.hasFocus=
!0;a.bindingHandlers.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.utils.setHtml(b,c())}};N("if");N("ifnot",!1,!0);N("with",!0,!1,function(a,c){return a.createChildContext(c)});var P={};a.bindingHandlers.options={init:function(b){if("select"!==a.utils.tagNameLower(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,c,d){function e(){return a.utils.arrayFilter(b.options,
function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?"function"==typeof a.ref?a.ref(b):a[b]:c}function h(c,d){if(r.length){var e=0<=a.utils.arrayIndexOf(r,a.selectExtensions.readValue(d[0]));a.utils.setOptionNodeSelectionState(d[0],e);n&&!e&&a.dependencyDetection.ignore(a.utils.triggerEvent,null,[b,"change"])}}var k=0!=b.length&&b.multiple?b.scrollTop:null,g=a.utils.unwrapObservable(c()),l=d.get("optionsIncludeDestroyed");c={};var m,r;r=b.multiple?
a.utils.arrayMap(e(),a.selectExtensions.readValue):0<=b.selectedIndex?[a.selectExtensions.readValue(b.options[b.selectedIndex])]:[];g&&("undefined"==typeof g.length&&(g=[g]),m=a.utils.arrayFilter(g,function(b){return l||b===q||null===b||!a.utils.unwrapObservable(b._destroy)}),d.has("optionsCaption")&&(g=a.utils.unwrapObservable(d.get("optionsCaption")),null!==g&&g!==q&&m.unshift(P)));var n=!1;c.beforeRemove=function(a){b.removeChild(a)};g=h;d.has("optionsAfterRender")&&(g=function(b,c){h(b,c);a.dependencyDetection.ignore(d.get("optionsAfterRender"),
null,[c[0],b!==P?b:q])});a.utils.setDomNodeChildrenFromArrayMapping(b,m,function(c,e,g){g.length&&(r=g[0].selected?[a.selectExtensions.readValue(g[0])]:[],n=!0);e=b.ownerDocument.createElement("option");c===P?(a.utils.setTextContent(e,d.get("optionsCaption")),a.selectExtensions.writeValue(e,q)):(g=f(c,d.get("optionsValue"),c),a.selectExtensions.writeValue(e,a.utils.unwrapObservable(g)),c=f(c,d.get("optionsText"),g),a.utils.setTextContent(e,c));return[e]},c,g);a.dependencyDetection.ignore(function(){d.get("valueAllowUnset")&&
d.has("value")?a.selectExtensions.writeValue(b,a.utils.unwrapObservable(d.get("value")),!0):(b.multiple?r.length&&e().length<r.length:r.length&&0<=b.selectedIndex?a.selectExtensions.readValue(b.options[b.selectedIndex])!==r[0]:r.length||0<=b.selectedIndex)&&a.utils.triggerEvent(b,"optionChange")});a.utils.ensureSelectElementIsRenderedCorrectly(b);k&&20<Math.abs(k-b.scrollTop)&&(b.scrollTop=k)}};a.bindingHandlers.options.optionValueDomDataKey=a.utils.domData.nextKey();a.bindingHandlers.selectedOptions=
{after:["options","foreach"],init:function(b,c,d){a.utils.registerEventHandler(b,"change",function(){var e=c(),f=[];a.utils.arrayForEach(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.selectExtensions.readValue(b))});a.expressionRewriting.writeValueToProperty(e,d,"selectedOptions",f)})},update:function(b,c){if("select"!=a.utils.tagNameLower(b))throw Error("values binding applies only to SELECT elements");var d=a.utils.unwrapObservable(c());d&&"number"==typeof d.length&&a.utils.arrayForEach(b.getElementsByTagName("option"),
function(b){var c=0<=a.utils.arrayIndexOf(d,a.selectExtensions.readValue(b));a.utils.setOptionNodeSelectionState(b,c)})}};a.expressionRewriting.twoWayBindings.selectedOptions=!0;a.bindingHandlers.style={update:function(b,c){var d=a.utils.unwrapObservable(c()||{});a.utils.objectForEach(d,function(c,d){d=a.utils.unwrapObservable(d);if(null===d||d===q||!1===d)d="";b.style[c]=d})}};a.bindingHandlers.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");
a.utils.registerEventHandler(b,"submit",function(a){var d,e=c();try{d=e.call(f.$object,b)}finally{!1===d&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.bindingHandlers.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.utils.setTextContent(b,c())}};a.virtualElements.allowedBindings.text=!0;(function(){if(w&&w.navigator)var b=function(a){if(a)return parseFloat(a[1])},c=w.opera&&w.opera.version&&parseInt(w.opera.version()),d=w.navigator.userAgent,e=b(d.match(/^(?:(?!chrome).)*version\/([^ ]*) safari/i)),
f=b(d.match(/Firefox\/([^ ]*)/));if(10>a.utils.ieVersion)var h=a.utils.domData.nextKey(),k=a.utils.domData.nextKey(),g=function(b){var c=this.activeElement;(c=c&&a.utils.domData.get(c,k))&&c(b)},l=function(b,c){var d=b.ownerDocument;a.utils.domData.get(d,h)||(a.utils.domData.set(d,h,!0),a.utils.registerEventHandler(d,"selectionchange",g));a.utils.domData.set(b,k,c)};a.bindingHandlers.textInput={init:function(b,d,g){var h=b.value,k,z,u=function(c){clearTimeout(k);z=k=q;var e=b.value;h!==e&&(DEBUG&&
c&&(b._ko_textInputProcessedEvent=c.type),h=e,a.expressionRewriting.writeValueToProperty(d(),g,"textInput",e))},t=function(a){k||(z=b.value,a=DEBUG?u.bind(b,{type:a.type}):u,k=setTimeout(a,4))},A=function(){var c=a.utils.unwrapObservable(d());if(null===c||c===q)c="";z!==q&&c===z?setTimeout(A,4):b.value!==c&&(h=c,b.value=c)},x=function(c,d){a.utils.registerEventHandler(b,c,d)};DEBUG&&a.bindingHandlers.textInput._forceUpdateOn?a.utils.arrayForEach(a.bindingHandlers.textInput._forceUpdateOn,function(a){"after"==
a.slice(0,5)?x(a.slice(5),t):x(a,u)}):10>a.utils.ieVersion?(x("propertychange",function(a){"value"===a.propertyName&&u(a)}),8==a.utils.ieVersion&&(x("keyup",u),x("keydown",u)),8<=a.utils.ieVersion&&(l(b,u),x("dragend",t))):(x("input",u),5>e&&"textarea"===a.utils.tagNameLower(b)?(x("keydown",t),x("paste",t),x("cut",t)):11>c?x("keydown",t):4>f&&(x("DOMAutoComplete",u),x("dragdrop",u),x("drop",u)));x("change",u);a.computed(A,null,{disposeWhenNodeIsRemoved:b})}};a.expressionRewriting.twoWayBindings.textInput=
!0;a.bindingHandlers.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.bindingHandlers.uniqueName={init:function(b,c){if(c()){var d="ko_unique_"+ ++a.bindingHandlers.uniqueName.currentIndex;a.utils.setElementName(b,d)}}};a.bindingHandlers.uniqueName.currentIndex=0;a.bindingHandlers.value={after:["options","foreach"],init:function(b,c,d){if("input"!=b.tagName.toLowerCase()||"checkbox"!=b.type&&"radio"!=b.type){var e=["change"],f=d.get("valueUpdate"),h=!1,k=null;f&&("string"==typeof f&&
(f=[f]),a.utils.arrayPushAll(e,f),e=a.utils.arrayGetDistinctValues(e));var g=function(){k=null;h=!1;var e=c(),g=a.selectExtensions.readValue(b);a.expressionRewriting.writeValueToProperty(e,d,"value",g)};!a.utils.ieVersion||"input"!=b.tagName.toLowerCase()||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.utils.arrayIndexOf(e,"propertychange")||(a.utils.registerEventHandler(b,"propertychange",function(){h=!0}),a.utils.registerEventHandler(b,"focus",function(){h=!1}),
a.utils.registerEventHandler(b,"blur",function(){h&&g()}));a.utils.arrayForEach(e,function(c){var d=g;a.utils.stringStartsWith(c,"after")&&(d=function(){k=a.selectExtensions.readValue(b);setTimeout(g,0)},c=c.substring(5));a.utils.registerEventHandler(b,c,d)});var l=function(){var e=a.utils.unwrapObservable(c()),g=a.selectExtensions.readValue(b);if(null!==k&&e===k)setTimeout(l,0);else if(e!==g)if("select"===a.utils.tagNameLower(b)){var f=d.get("valueAllowUnset"),g=function(){a.selectExtensions.writeValue(b,
e,f)};g();f||e===a.selectExtensions.readValue(b)?setTimeout(g,0):a.dependencyDetection.ignore(a.utils.triggerEvent,null,[b,"change"])}else a.selectExtensions.writeValue(b,e)};a.computed(l,null,{disposeWhenNodeIsRemoved:b})}else a.applyBindingAccessorsToNode(b,{checkedValue:c})},update:function(){}};a.expressionRewriting.twoWayBindings.value=!0;a.bindingHandlers.visible={update:function(b,c){var d=a.utils.unwrapObservable(c()),e="none"!=b.style.display;d&&!e?b.style.display="":!d&&e&&(b.style.display=
"none")}};(function(b){a.bindingHandlers[b]={init:function(c,d,e,f,h){return a.bindingHandlers.event.init.call(this,c,function(){var a={};a[b]=d();return a},e,f,h)}}})("click");a.templateEngine=function(){};a.templateEngine.prototype.renderTemplateSource=function(a,c,d){throw Error("Override renderTemplateSource");};a.templateEngine.prototype.createJavaScriptEvaluatorBlock=function(a){throw Error("Override createJavaScriptEvaluatorBlock");};a.templateEngine.prototype.makeTemplateSource=function(b,
c){if("string"==typeof b){c=c||y;var d=c.getElementById(b);if(!d)throw Error("Cannot find template with ID "+b);return new a.templateSources.domElement(d)}if(1==b.nodeType||8==b.nodeType)return new a.templateSources.anonymousTemplate(b);throw Error("Unknown template type: "+b);};a.templateEngine.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d)};a.templateEngine.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?
!0:this.makeTemplateSource(a,c).data("isRewritten")};a.templateEngine.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.exportSymbol("templateEngine",a.templateEngine);a.templateRewriting=function(){function b(b,c,d,k){b=a.expressionRewriting.parseObjectLiteral(b);for(var g=a.expressionRewriting.bindingRewriteValidators,l=0;l<b.length;l++){var m=b[l].key;if(g.hasOwnProperty(m)){var r=g[m];if("function"===typeof r){if(m=r(b[l].value))throw Error(m);
}else if(!r)throw Error("This template engine does not support the '"+m+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.expressionRewriting.preProcessBindings(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return k.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{ensureTemplateIsRewritten:function(b,
c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.templateRewriting.memoizeBindingAttributeSyntax(b,c)},d)},memoizeBindingAttributeSyntax:function(a,f){return a.replace(c,function(a,c,d,e,m){return b(m,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",f)})},applyMemoizedBindingsToNextSibling:function(b,c){return a.memoization.memoize(function(d,k){var g=d.nextSibling;g&&g.nodeName.toLowerCase()===c&&a.applyBindingAccessorsToNode(g,b,k)})}}}();a.exportSymbol("__tr_ambtns",
a.templateRewriting.applyMemoizedBindingsToNextSibling);(function(){a.templateSources={};a.templateSources.domElement=function(a){this.domElement=a};a.templateSources.domElement.prototype.text=function(){var b=a.utils.tagNameLower(this.domElement),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.domElement[b];var c=arguments[0];"innerHTML"===b?a.utils.setHtml(this.domElement,c):this.domElement[b]=c};var b=a.utils.domData.nextKey()+"_";a.templateSources.domElement.prototype.data=
function(c){if(1===arguments.length)return a.utils.domData.get(this.domElement,b+c);a.utils.domData.set(this.domElement,b+c,arguments[1])};var c=a.utils.domData.nextKey();a.templateSources.anonymousTemplate=function(a){this.domElement=a};a.templateSources.anonymousTemplate.prototype=new a.templateSources.domElement;a.templateSources.anonymousTemplate.prototype.constructor=a.templateSources.anonymousTemplate;a.templateSources.anonymousTemplate.prototype.text=function(){if(0==arguments.length){var b=
a.utils.domData.get(this.domElement,c)||{};b.textData===q&&b.containerData&&(b.textData=b.containerData.innerHTML);return b.textData}a.utils.domData.set(this.domElement,c,{textData:arguments[0]})};a.templateSources.domElement.prototype.nodes=function(){if(0==arguments.length)return(a.utils.domData.get(this.domElement,c)||{}).containerData;a.utils.domData.set(this.domElement,c,{containerData:arguments[0]})};a.exportSymbol("templateSources",a.templateSources);a.exportSymbol("templateSources.domElement",
a.templateSources.domElement);a.exportSymbol("templateSources.anonymousTemplate",a.templateSources.anonymousTemplate)})();(function(){function b(b,c,d){var e;for(c=a.virtualElements.nextSibling(c);b&&(e=b)!==c;)b=a.virtualElements.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],h=e.parentNode,k=a.bindingProvider.instance,s=k.preprocessNode;if(s){b(e,f,function(a,b){var c=a.previousSibling,d=s.call(k,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;
if(!e)return;e===f?c.push(e):(c.push(e,f),a.utils.fixUpContinuousNodeArray(c,h))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.applyBindings(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.memoization.unmemoizeDomNodeAndDescendants(b,[d])});a.utils.fixUpContinuousNodeArray(c,h)}}function d(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,f,k,n){n=n||{};var p=b&&d(b),p=p&&p.ownerDocument,s=n.templateEngine||h;a.templateRewriting.ensureTemplateIsRewritten(f,s,p);f=s.renderTemplate(f,
k,n,p);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");p=!1;switch(e){case "replaceChildren":a.virtualElements.setDomNodeChildren(b,f);p=!0;break;case "replaceNode":a.utils.replaceDomNodes(b,f);p=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+e);}p&&(c(f,k),n.afterRender&&a.dependencyDetection.ignore(n.afterRender,null,[f,k.$object]));return f}function f(b,c,d){return a.isObservable2(b)?
b():"function"===typeof b?b(c,d):b}var h;a.setTemplateEngine=function(b){if(b!=q&&!(b instanceof a.templateEngine))throw Error("templateEngine must inherit from ko.templateEngine");h=b};a.renderTemplate=function(b,c,k,r,n){k=k||{};if((k.templateEngine||h)==q)throw Error("Set a template engine before calling renderTemplate");n=n||"replaceChildren";if(r){var p=d(r);return a.dependentObservable(function(){var h=c&&c instanceof a.bindingContext?c:new a.bindingContext(a.utils.unwrapObservable(c)),q=f(b,
h.$object,h),h=e(r,n,q,h,k);"replaceNode"==n&&(r=h,p=d(r))},null,{disposeWhen:function(){return!p||!a.utils.domNodeIsAttachedToDocument(p)},disposeWhenNodeIsRemoved:p&&"replaceNode"==n?p.parentNode:p})}return a.memoization.memoize(function(d){a.renderTemplate(b,c,k,d,"replaceNode")})};a.renderTemplateForEach=function(b,d,h,k,n){var p,s=function(a,c){p=n.createChildContext(a,h.as,function(a){a.$index=c});var d=f(b,a,p);return e(null,"ignoreTargetNode",d,p,h)},t=function(a,b,d){c(b,p);h.afterRender&&
h.afterRender(b,a)};return a.dependentObservable(function(){var b=a.utils.unwrapObservable(d)||[];"undefined"==typeof b.length&&(b=[b]);b=a.utils.arrayFilter(b,function(b){return h.includeDestroyed||b===q||null===b||!a.utils.unwrapObservable(b._destroy)});a.dependencyDetection.ignore(a.utils.setDomNodeChildrenFromArrayMapping,null,[k,b,s,h,t])},null,{disposeWhenNodeIsRemoved:k})};var k=a.utils.domData.nextKey();a.bindingHandlers.template={init:function(b,c){var d=a.utils.unwrapObservable(c());"string"==
typeof d||d.name?a.virtualElements.emptyNode(b):(d=a.virtualElements.childNodes(b),d=a.utils.moveCleanedNodesToContainerElement(d),(new a.templateSources.anonymousTemplate(b)).nodes(d));return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var h=c(),s;c=a.utils.unwrapObservable(h);d=!0;e=null;"string"==typeof c?c={}:(h=c.name,"if"in c&&(d=a.utils.unwrapObservable(c["if"])),d&&"ifnot"in c&&(d=!a.utils.unwrapObservable(c.ifnot)),s=a.utils.unwrapObservable(c.data));"foreach"in c?e=a.renderTemplateForEach(h||
b,d&&c.foreach||[],c,b,f):d?(f="data"in c?f.createChildContext(s,c.as):f,e=a.renderTemplate(h||b,f,c,b)):a.virtualElements.emptyNode(b);f=e;(s=a.utils.domData.get(b,k))&&"function"==typeof s.dispose&&s.dispose();a.utils.domData.set(b,k,f&&f.isActive()?f:q)}};a.expressionRewriting.bindingRewriteValidators.template=function(b){b=a.expressionRewriting.parseObjectLiteral(b);return 1==b.length&&b[0].unknown||a.expressionRewriting.keyValueArrayContainsKey(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};
a.virtualElements.allowedBindings.template=!0})();a.exportSymbol("setTemplateEngine",a.setTemplateEngine);a.exportSymbol("renderTemplate",a.renderTemplate);a.utils.findMovesInArrayComparison=function(a,c,d){if(a.length&&c.length){var e,f,h,k,g;for(e=f=0;(!d||e<d)&&(k=a[f]);++f){for(h=0;g=c[h];++h)if(k.value===g.value){k.moved=g.index;g.moved=k.index;c.splice(h,1);e=h=0;break}e+=h}}};a.utils.compareArrays=function(){function b(b,d,e,f,h){var k=Math.min,g=Math.max,l=[],m,r=b.length,n,p=d.length,q=p-
r||1,t=r+p+1,u,w,A;for(m=0;m<=r;m++)for(w=u,l.push(u=[]),A=k(p,m+q),n=g(0,m-1);n<=A;n++)u[n]=n?m?b[m-1]===d[n-1]?w[n-1]:k(w[n]||t,u[n-1]||t)+1:n+1:m+1;k=[];g=[];q=[];m=r;for(n=p;m||n;)p=l[m][n]-1,n&&p===l[m][n-1]?g.push(k[k.length]={status:e,value:d[--n],index:n}):m&&p===l[m-1][n]?q.push(k[k.length]={status:f,value:b[--m],index:m}):(--n,--m,h.sparse||k.push({status:"retained",value:d[n]}));a.utils.findMovesInArrayComparison(g,q,10*r);return k.reverse()}return function(a,d,e){e="boolean"===typeof e?
{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<=d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.exportSymbol("utils.compareArrays",a.utils.compareArrays);(function(){function b(b,c,f,h,k){var g=[],l=a.dependentObservable(function(){var l=c(f,k,a.utils.fixUpContinuousNodeArray(g,b))||[];0<g.length&&(a.utils.replaceDomNodes(g,l),h&&a.dependencyDetection.ignore(h,null,[f,l,k]));g.length=0;a.utils.arrayPushAll(g,l)},null,{disposeWhenNodeIsRemoved:b,disposeWhen:function(){return!a.utils.anyDomNodeIsAttachedToDocument(g)}});
return{mappedNodes:g,dependentObservable:l.isActive()?l:q}}var c=a.utils.domData.nextKey();a.utils.setDomNodeChildrenFromArrayMapping=function(d,e,f,h,k){function g(b,c){v=r[c];u!==c&&(x[b]=v);v.indexObservable(u++);a.utils.fixUpContinuousNodeArray(v.mappedNodes,d);s.push(v);A.push(v)}function l(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.utils.arrayForEach(c[d].mappedNodes,function(a){b(a,d,c[d].arrayEntry)})}e=e||[];h=h||{};var m=a.utils.domData.get(d,c)===q,r=a.utils.domData.get(d,c)||[],
n=a.utils.arrayMap(r,function(a){return a.arrayEntry}),p=a.utils.compareArrays(n,e,h.dontLimitMoves),s=[],t=0,u=0,w=[],A=[];e=[];for(var x=[],n=[],v,y=0,B,D;B=p[y];y++)switch(D=B.moved,B.status){case "deleted":D===q&&(v=r[t],v.dependentObservable&&v.dependentObservable.dispose(),w.push.apply(w,a.utils.fixUpContinuousNodeArray(v.mappedNodes,d)),h.beforeRemove&&(e[y]=v,A.push(v)));t++;break;case "retained":g(y,t++);break;case "added":D!==q?g(y,D):(v={arrayEntry:B.value,indexObservable:a.observable2(u++)},
s.push(v),A.push(v),m||(n[y]=v))}l(h.beforeMove,x);a.utils.arrayForEach(w,h.beforeRemove?a.cleanNode:a.removeNode);for(var y=0,m=a.virtualElements.firstChild(d),E;v=A[y];y++){v.mappedNodes||a.utils.extend(v,b(d,f,v.arrayEntry,k,v.indexObservable));for(t=0;p=v.mappedNodes[t];m=p.nextSibling,E=p,t++)p!==m&&a.virtualElements.insertAfter(d,p,E);!v.initialized&&k&&(k(v.arrayEntry,v.mappedNodes,v.indexObservable),v.initialized=!0)}l(h.beforeRemove,e);l(h.afterMove,x);l(h.afterAdd,n);a.utils.domData.set(d,
c,s)}})();a.exportSymbol("utils.setDomNodeChildrenFromArrayMapping",a.utils.setDomNodeChildrenFromArrayMapping);a.nativeTemplateEngine=function(){this.allowTemplateRewriting=!1};a.nativeTemplateEngine.prototype=new a.templateEngine;a.nativeTemplateEngine.prototype.constructor=a.nativeTemplateEngine;a.nativeTemplateEngine.prototype.renderTemplateSource=function(b,c,d){if(c=(9>a.utils.ieVersion?0:b.nodes)?b.nodes():null)return a.utils.makeArray(c.cloneNode(!0).childNodes);b=b.text();return a.utils.parseHtmlFragment(b)};
a.nativeTemplateEngine.instance=new a.nativeTemplateEngine;a.setTemplateEngine(a.nativeTemplateEngine.instance);a.exportSymbol("nativeTemplateEngine",a.nativeTemplateEngine);(function(){a.jqueryTmplTemplateEngine=function(){var a=this.jQueryTmplVersion=function(){if(!t||!t.tmpl)return 0;try{if(0<=t.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f){f=f||{};if(2>a)throw Error("Your version of jQueryInstance.tmpl is too old. Please upgrade to jQueryInstance.tmpl 1.0.0pre or later.");
var h=b.data("precompiled");h||(h=b.text()||"",h=t.template(null,"{{ko_with $item.koBindingContext}}"+h+"{{/ko_with}}"),b.data("precompiled",h));b=[e.$object];e=t.extend({koBindingContext:e},f.templateOptions);e=t.tmpl(h,b,e);e.appendTo(y.createElement("div"));t.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){y.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(t.tmpl.tag.ko_code=
{open:"__.push($1 || '');"},t.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.jqueryTmplTemplateEngine.prototype=new a.templateEngine;a.jqueryTmplTemplateEngine.prototype.constructor=a.jqueryTmplTemplateEngine;var b=new a.jqueryTmplTemplateEngine;0<b.jQueryTmplVersion&&a.setTemplateEngine(b);a.exportSymbol("jqueryTmplTemplateEngine",a.jqueryTmplTemplateEngine)})()})})();})();
